--read the user's family ID safely
CREATE OR REPLACE FUNCTION public.get_my_family_id()
RETURNS UUID AS $$
  SELECT family_id FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

-- Drop the broken infinite-loop policy from first schema
DROP POLICY IF EXISTS "Users can view family members" ON public.profiles;

-- Re-create the SELECT policy
CREATE POLICY "Users can view family members"
ON public.profiles FOR SELECT
TO authenticated
USING ( family_id = public.get_my_family_id() );


-- FEATURE 1: ACCESSIBLE CONTACT AND BIRTHDAY DIRECTORY
CREATE TABLE public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id UUID NOT NULL, -- Ties the contact to a specific family unit
    first_name TEXT NOT NULL,
    last_name TEXT,
    phone_number TEXT,
    email TEXT,
    birthday DATE,
    relationship_notes TEXT,--'Uncle on mother's side'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- FEATURE 3: VISUAL FAMILY TREE HISTORY ENGINE
CREATE TABLE public.family_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id UUID NOT NULL,
    person_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    relative_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    relationship_type TEXT NOT NULL CHECK (relationship_type IN ('parent', 'child', 'spouse', 'sibling')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    -- Prevent mapping a person to themselves
    CONSTRAINT self_relationship_check CHECK (person_id != relative_id)
);


-- ENABLE RLS
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_relationships ENABLE ROW LEVEL SECURITY;


-- Contacts Policies
CREATE POLICY "Family members can view contacts" ON public.contacts
    FOR SELECT TO authenticated USING (family_id = public.get_my_family_id());
CREATE POLICY "Family members can add contacts" ON public.contacts
    FOR INSERT TO authenticated WITH CHECK (family_id = public.get_my_family_id());
CREATE POLICY "Family members can manage contacts" ON public.contacts
    FOR ALL TO authenticated USING (family_id = public.get_my_family_id());


-- Family Tree Relationship Map Policies
CREATE POLICY "Family members can view family tree maps" ON public.family_relationships
    FOR SELECT TO authenticated USING (family_id = public.get_my_family_id());
CREATE POLICY "Family members can modify tree relationships" ON public.family_relationships
    FOR ALL TO authenticated USING (family_id = public.get_my_family_id());
